server:
  port: 8082
spring:
  application:
    name: hh-explorer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 15000
  instance:
    instance-id:
      ${spring:application:name}:${server:port}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true
    env:
      enabled: true
logging:
  level:
    root: info
  file:
    name: target/app.log
info:
  app:
    version: @project.version@
    author: Sokolov
    description: Head Hunter Explorer

hh:
  service-vacancy-url: https://api.hh.ru/vacancies/
  prof-map:
    1: 4
    2: 5
    3: 62
    4: 70
    5: 10
    6: 12
    7: 25
    8: 34
    9: 36
    10: 73
    11: 96
    12: 104
    13: 107
    14: 112
    15: 113
    16: 114
    17: 116
    18: 121
    19: 124
    20: 125
    21: 126
    22: 26
    23: 36
    24: 37
    25: 38
    26: 53
    27: 80
    28: 87
    29: 125
    30: 135
    31: 15
    32: 19
    33: 24
    34: 29
    35: 42
    36: 64
    37: 65
    38: 133
    39: 23
    40: 79
    41: 101
    42: 132
    43: 21
    44: 32
    45: 58
    46: 89
    47: 90
    48: 130
    49: 66
    50: 119
  area-map:
    1: 1
    2: 2
    3: 99
    4: 3
    5: 4
    6: 10
    7: 11
    8: 12
    9: 14
    10: 15
    11: 17
    12: 19
    13: 20
    14: 22
    15: 23
    16: 24
    17: 25
    18: 26
    19: 29
    20: 31
    21: 32
    22: 35
    23: 39
    24: 41
    25: 42
    26: 43
    27: 44
    28: 46
    29: 47
    30: 49
    31: 51
    32: 52
    33: 53
    34: 54
    35: 55
    36: 56
    37: 58
    38: 60
    39: 61
    40: 63
    41: 64
    42: 66
    43: 67
    44: 68
    45: 69
    46: 70
    47: 71
    48: 72
    49: 73
    50: 75






























































